jobs:
  clippy:
    uses: ./workflows/cargo.yml
    with:
      toolchain: ${{ inputs.toolchain }}
      components: clippy
      command: clippy
      args: --workspace --all-targets --all-features --locked -- -D warnings

on:
  workflow_call:
    inputs:
      toolchain:
        default: stable
        type: string
