jobs:
  staging:
    uses: ./.github/workflows/staging.yml
  success-staging:
    needs: [staging]
    runs-on: ubuntu-latest
    steps:
    - run: true

on:
  pull_request:
    branches: [prīmum]
  push:
    branches: [staging, trying]
