jobs:
  nightly:
    uses: ./.github/workflows/nightly.yml
  success-nightly:
    needs: [nightly]
    runs-on: ubuntu-latest
    steps:
    - run: true

on:
  pull_request:
    branches: [main]
  push:
    branches: [staging, trying]
