env:
  RUST_BACKTRACE: 1

jobs:
  cargo:
    name: cargo +${{ inputs.toolchain }} ${{ inputs.command }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ inputs.toolchain }}
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}
    - uses: actions-rs/cargo@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        command: ${{ inputs.command }}
        args: ${{ inputs.args }}

on:
  workflow_call:
    inputs:
      toolchain:
        default: stable
        type: string
      components:
        default: ''
        type: string
      targets:
        default: ''
        type: string
      command:
        required: true
        type: string
      args:
        default: ''
        type: string
