jobs:
  clippy:
    name: cargo +${{ inputs.toolchain }} lints clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: clippy
    - run:
        cargo install
          --git https://github.com/soramitsu/iroha2-cargo_lints --rev 2f8cad22
    - run:
        cargo lints clippy
          --workspace --all-targets --all-features --locked -- -D warnings

on:
  workflow_call:
    inputs:
      toolchain:
        default: stable
        type: string
