env:
  RUST_BACKTRACE: 1

jobs:
  check:
    name: cargo deny check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-deny
    - run:
        cargo deny
          --workspace --all-features --locked
          check --deny warnings --allow duplicate

on:
  workflow_call:
