jobs:
  docsrs:
    name: cargo +nightly doc --cfg docsrs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - run: cargo doc --no-deps --workspace --all-features --locked
    env:
      RUSTDOCFLAGS: --cfg=docsrs -Dwarnings

on:
  workflow_call:
