jobs:
  fmt:
    name: cargo +${{ inputs.toolchain }} fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: rustfmt
    - run: cargo fmt -- --check

on:
  workflow_call:
    inputs:
      toolchain:
        default: stable
        type: string
