jobs:
  fmt:
    name: cargo +${{ inputs.toolchain }} fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ inputs.toolchain }}
        components: rustfmt
    - run: cargo fmt -- --check

on:
  workflow_call:
    inputs:
      toolchain:
        default: stable
        type: string
