jobs:
  minimal-versions:
    name: cargo minimal-versions check --workspace
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: hecrj/setup-rust-action@v1
    - uses: taiki-e/install-action@v1
      with:
        tool: cargo-hack,cargo-minimal-versions
    - uses: actions-rs/cargo@v1
      with:
        command: minimal-versions
        args: check --workspace --all-features

on:
  workflow_call:
