jobs:
  minimal-versions:
    name: cargo minimal-versions check --workspace
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
    - run: rustup toolchain install nightly
    - uses: taiki-e/install-action@v1
      with:
        tool: cargo-hack,cargo-minimal-versions
    - run: cargo minimal-versions check --workspace --all-features

on:
  workflow_call:
