jobs:
  test:
    strategy:
      matrix:
        platform:
        - { os: macos-latest, target: x86_64-apple-darwin }
        - { os: ubuntu-latest, target: i686-unknown-linux-gnu }
        - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
        - { os: windows-latest, target: i686-pc-windows-msvc }
        - { os: windows-latest, target: x86_64-pc-windows-msvc }
      fail-fast: false
    runs-on: ${{ matrix.platform.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
        targets: ${{ matrix.platform.target }}
    - run: sudo apt install -y gcc-multilib
      if: ${{ matrix.platform.target == 'i686-unknown-linux-gnu' }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --workspace --locked --all-features --target ${{ matrix.platform.target }}

on:
  workflow_call:
