jobs:
  test:
    strategy:
      matrix:
        platform:
        - { os: macos-latest, target: x86_64-apple-darwin }
        - { os: ubuntu-latest, target: i686-unknown-linux-gnu }
        - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
        - { os: windows-latest, target: i686-pc-windows-msvc }
        - { os: windows-latest, target: x86_64-pc-windows-msvc }
    uses: ./.github/workflows/test.yml
    with:
      runs-on: ${{ matrix.platform.os }}
      targets: ${{ matrix.platform.target }}
      args: --target ${{ matrix.platform.target }}

on:
  workflow_call:
