jobs:
  pull_request:
    uses: ./.github/workflows/pull_request.yml
  staging:
    uses: ./.github/workflows/staging.yml
  nightly:
    uses: ./.github/workflows/nightly.yml
  success:
    needs: [pull_request, staging, nightly]
    runs-on: ubuntu-latest
    steps:
    - run: true

on:
  pull_request:
    branches: [prīmum]
  push:
    branches: [staging, trying]
