jobs:
  platforms:
    uses: ./.github/workflows/platforms.yml
  check-features:
    uses: ./.github/workflows/features.yml
    with:
      skip: ${{ inputs.skip-features }}
  updates:
    uses: ./.github/workflows/updates.yml
  minimal-versions:
    uses: ./.github/workflows/minimal-versions.yml
  coverage:
    uses: ./.github/workflows/coverage.yml

on:
  workflow_call:
    inputs:
      skip-features:
        default: ''
        type: string
