env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: cargo +${{ inputs.toolchain }} test ${{ inputs.args }}
    runs-on: ${{ inputs.runs-on }}
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ inputs.toolchain }}
        targets: ${{ inputs.targets }}
    - uses: actions-rs/cargo@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        command: test
        args: --workspace --locked --all-features ${{ inputs.args }}

on:
  workflow_call:
    inputs:
      toolchain:
        default: stable
        type: string
      args:
        required: false
        type: string
      runs-on:
        default: ubuntu-latest
        type: string
      targets:
        required: false
        type: string
